// Generated by cargo-kcfg. Do not edit by hand.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Tristate {
No,
Module,
Yes,
}

impl Tristate {
pub const fn is_enabled(self) -> bool {
matches!(self, Self::Yes | Self::Module)
}
}

pub const CONFIG_FOO: bool = true;
pub const CONFIG_BUFFER_SIZE: u16 = 256;
pub const CONFIG_BOARD_NAME: &'static str = "workspace-virt";
pub const CONFIG_BUS: bool = true;
pub const CONFIG_UART: bool = true;
