[package]
name = "cargo-kcfg-macros"
version = "0.0.1"
edition = "2024"
authors = ["CoreEmpiric"]
license = "MIT"
description = "Proc-macro include for cargo-kcfg generated CONFIG_* constants"
readme = "README.md"
homepage = "https://github.com/coreempiric/cargo-kcfg"
documentation = "https://docs.rs/cargo-kcfg-macros"
keywords = ["kconfig", "cargo", "embedded", "configuration"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
cargo-kcfg = { path = "..", version = "0.0.2" }
proc-macro2 = "1"
quote = "1"
