use crate::domain::{EvaluatedConfig, SymbolType, Tristate, Value, config_ident};

/// Generated artefacts produced from an evaluated configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    pub config_rs: String,
    pub dotconfig: String,
    pub rustc_cfgs: Vec<String>,
    pub rustc_check_cfgs: Vec<String>,
}

pub fn generate(evaluated: &EvaluatedConfig) -> Generated {
    let mut config_rs = String::from(
        "// Generated by cargo-kconfig. Do not edit by hand.\n\
         \n\
         #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub enum Tristate {\n\
             No,\n\
             Module,\n\
             Yes,\n\
         }\n\
         \n\
         impl Tristate {\n\
             pub const fn is_enabled(self) -> bool {\n\
                 matches!(self, Self::Yes | Self::Module)\n\
             }\n\
         }\n\n",
    );
    let mut dotconfig = String::from("# Generated by cargo-kconfig\n");
    let mut rustc_cfgs = Vec::new();
    let mut rustc_check_cfgs = Vec::new();

    for symbol in evaluated.table.iter() {
        let Some(kind) = symbol.kind else {
            continue;
        };
        let Some(value) = evaluated.values.get(&symbol.name) else {
            continue;
        };
        let ident = config_ident(&symbol.name);
        config_rs.push_str(&rust_const(&ident, kind, value));
        config_rs.push('\n');
        dotconfig.push_str(&dotconfig_line(&ident, kind, value));
        dotconfig.push('\n');

        if matches!(kind, SymbolType::Bool | SymbolType::Tristate) {
            rustc_check_cfgs.push(format!("cfg({ident})"));
            if value.to_tristate().is_enabled() {
                rustc_cfgs.push(ident);
            }
        }
    }

    Generated {
        config_rs,
        dotconfig,
        rustc_cfgs,
        rustc_check_cfgs,
    }
}

fn rust_const(ident: &str, kind: SymbolType, value: &Value) -> String {
    match kind {
        SymbolType::Bool => {
            let v = matches!(value, Value::Bool(true)) || value.to_tristate() == Tristate::Yes;
            format!("pub const {ident}: bool = {v};")
        }
        SymbolType::Tristate => {
            let t = value.to_tristate();
            let variant = match t {
                Tristate::Yes => "Yes",
                Tristate::Module => "Module",
                Tristate::No => "No",
            };
            format!("pub const {ident}: Tristate = Tristate::{variant};")
        }
        SymbolType::Int | SymbolType::Hex => {
            let n = value.as_u32().unwrap_or(0);
            if kind == SymbolType::Hex {
                format!("pub const {ident}: u32 = {n:#x};")
            } else {
                format!("pub const {ident}: u32 = {n};")
            }
        }
        SymbolType::String => {
            let s = value.as_string();
            format!("pub const {ident}: &'static str = {s:?};")
        }
    }
}

fn dotconfig_line(ident: &str, kind: SymbolType, value: &Value) -> String {
    match kind {
        SymbolType::Bool => {
            if value.to_tristate().is_enabled() {
                format!("{ident}=y")
            } else {
                format!("# {ident} is not set")
            }
        }
        SymbolType::Tristate => match value.to_tristate() {
            Tristate::Yes => format!("{ident}=y"),
            Tristate::Module => format!("{ident}=m"),
            Tristate::No => format!("# {ident} is not set"),
        },
        SymbolType::Int | SymbolType::Hex | SymbolType::String => {
            format!("{ident}={value}")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::domain::{
        AssignmentSet, DefaultValue, Expression, Limits, Symbol, SymbolTable, SymbolType, Value,
        evaluate,
    };

    #[test]
    fn emits_typed_consts_and_dotconfig() {
        let limits = Limits::default();
        let mut table = SymbolTable::new();
        let mut foo = Symbol::new("FOO", limits)
            .unwrap()
            .with_type(SymbolType::Bool);
        foo.defaults.push(DefaultValue {
            value: Expression::Constant(Value::Bool(true)),
            condition: None,
        });
        let mut size = Symbol::new("BUFFER_SIZE", limits)
            .unwrap()
            .with_type(SymbolType::Int);
        size.defaults.push(DefaultValue {
            value: Expression::Constant(Value::Int(128)),
            condition: None,
        });
        let mut name = Symbol::new("BOARD_NAME", limits)
            .unwrap()
            .with_type(SymbolType::String);
        name.defaults.push(DefaultValue {
            value: Expression::Constant(Value::String("qemu".into())),
            condition: None,
        });
        table.insert(foo, limits).unwrap();
        table.insert(size, limits).unwrap();
        table.insert(name, limits).unwrap();
        let evaluated = evaluate(table, &AssignmentSet::new(), limits).unwrap();
        let generated = generate(&evaluated);
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_FOO: bool = true;")
        );
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_BUFFER_SIZE: u32 = 128;")
        );
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_BOARD_NAME: &'static str = \"qemu\";")
        );
        assert!(generated.dotconfig.contains("CONFIG_FOO=y"));
        assert!(generated.rustc_cfgs.contains(&"CONFIG_FOO".to_string()));
    }
}
