//! Artefact generation from an evaluated configuration.
//!
//! Last stage of [`crate::infra::pipeline::Pipeline`]:
//! [`CodeGenerator::generate`] emits `config.rs`, `.config`, and `rustc-cfg` names.

use crate::domain::{
    EvaluatedConfig, RangeBound, Symbol, SymbolType, Tristate, Value, config_ident,
};

/// Generated artefacts produced from an evaluated configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    pub config_rs: String,
    pub dotconfig: String,
    pub rustc_cfgs: Vec<String>,
    pub rustc_check_cfgs: Vec<String>,
}

impl Generated {
    /// Print `cargo:rustc-check-cfg` / `cargo:rustc-cfg` lines for a `build.rs`.
    pub fn print_cargo_cfg_lines(&self) {
        for cfg in &self.rustc_check_cfgs {
            println!("cargo:rustc-check-cfg={cfg}");
        }
        for cfg in &self.rustc_cfgs {
            println!("cargo:rustc-cfg={cfg}");
        }
    }
}

/// Turns an [`EvaluatedConfig`] into Rust constants, `.config` text, and cfg names.
pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, evaluated: &EvaluatedConfig) -> Generated {
        let mut config_rs = String::from(
            "// Generated by cargo-kconfig. Do not edit by hand.\n\
             \n\
             #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
             pub enum Tristate {\n\
                 No,\n\
                 Module,\n\
                 Yes,\n\
             }\n\
             \n\
             impl Tristate {\n\
                 pub const fn is_enabled(self) -> bool {\n\
                     matches!(self, Self::Yes | Self::Module)\n\
                 }\n\
             }\n\n",
        );
        let mut dotconfig = String::from("# Generated by cargo-kconfig\n");
        let mut rustc_cfgs = Vec::new();
        let mut rustc_check_cfgs = Vec::new();

        for symbol in evaluated.table.iter() {
            let Some(kind) = symbol.kind else {
                continue;
            };
            let Some(value) = evaluated.values.get(&symbol.name) else {
                continue;
            };
            let ident = config_ident(&symbol.name);
            config_rs.push_str(&self.rust_const(&ident, kind, value, symbol, evaluated));
            config_rs.push('\n');
            dotconfig.push_str(&self.dotconfig_line(&ident, kind, value));
            dotconfig.push('\n');

            if matches!(kind, SymbolType::Bool | SymbolType::Tristate) {
                rustc_check_cfgs.push(format!("cfg({ident})"));
                if value.to_tristate().is_enabled() {
                    rustc_cfgs.push(ident);
                }
            }
        }

        Generated {
            config_rs,
            dotconfig,
            rustc_cfgs,
            rustc_check_cfgs,
        }
    }

    fn rust_const(
        &self,
        ident: &str,
        kind: SymbolType,
        value: &Value,
        symbol: &Symbol,
        evaluated: &EvaluatedConfig,
    ) -> String {
        match kind {
            SymbolType::Bool => {
                let v = matches!(value, Value::Bool(true)) || value.to_tristate() == Tristate::Yes;
                format!("pub const {ident}: bool = {v};")
            }
            SymbolType::Tristate => {
                let t = value.to_tristate();
                let variant = match t {
                    Tristate::Yes => "Yes",
                    Tristate::Module => "Module",
                    Tristate::No => "No",
                };
                format!("pub const {ident}: Tristate = Tristate::{variant};")
            }
            SymbolType::Int | SymbolType::Hex => {
                self.integer_const(ident, kind == SymbolType::Hex, value, symbol, evaluated)
            }
            SymbolType::String => {
                let s = value.as_string();
                format!("pub const {ident}: &'static str = {s:?};")
            }
        }
    }

    fn integer_const(
        &self,
        ident: &str,
        hex: bool,
        value: &Value,
        symbol: &Symbol,
        evaluated: &EvaluatedConfig,
    ) -> String {
        let n = match Self::value_as_i128(value) {
            Some(n) => n,
            None => return format!("pub const {ident}: i64 = 0;"),
        };
        let (lo, hi) = self.integer_bounds(n, symbol, evaluated);
        let ty = Self::rust_int_type(lo, hi);
        if hex && n >= 0 {
            format!("pub const {ident}: {ty} = {n:#x};")
        } else {
            format!("pub const {ident}: {ty} = {n};")
        }
    }

    fn value_as_i128(value: &Value) -> Option<i128> {
        match value {
            Value::Int(n) => Some(i128::from(*n)),
            Value::Hex(n) => Some(i128::from(*n)),
            _ => value.as_int().ok().map(i128::from),
        }
    }

    fn integer_bounds(
        &self,
        value: i128,
        symbol: &Symbol,
        evaluated: &EvaluatedConfig,
    ) -> (i128, i128) {
        let mut lo = value;
        let mut hi = value;
        for range in &symbol.ranges {
            if let Some(min) = self.bound_as_i128(&range.min, evaluated) {
                lo = lo.min(min);
                hi = hi.max(min);
            }
            if let Some(max) = self.bound_as_i128(&range.max, evaluated) {
                lo = lo.min(max);
                hi = hi.max(max);
            }
        }
        (lo, hi)
    }

    fn bound_as_i128(&self, bound: &RangeBound, evaluated: &EvaluatedConfig) -> Option<i128> {
        match bound {
            RangeBound::Number(n) => Some(i128::from(*n)),
            RangeBound::Symbol(name) => evaluated.get(name).and_then(Self::value_as_i128),
        }
    }

    /// Smallest explicit integer type that can hold every value in `lo..=hi`.
    fn rust_int_type(lo: i128, hi: i128) -> &'static str {
        if lo >= 0 {
            if hi <= i128::from(u8::MAX) {
                "u8"
            } else if hi <= i128::from(u16::MAX) {
                "u16"
            } else if hi <= i128::from(u32::MAX) {
                "u32"
            } else {
                "u64"
            }
        } else if lo >= i128::from(i8::MIN) && hi <= i128::from(i8::MAX) {
            "i8"
        } else if lo >= i128::from(i16::MIN) && hi <= i128::from(i16::MAX) {
            "i16"
        } else if lo >= i128::from(i32::MIN) && hi <= i128::from(i32::MAX) {
            "i32"
        } else {
            "i64"
        }
    }

    fn dotconfig_line(&self, ident: &str, kind: SymbolType, value: &Value) -> String {
        match kind {
            SymbolType::Bool => {
                if value.to_tristate().is_enabled() {
                    format!("{ident}=y")
                } else {
                    format!("# {ident} is not set")
                }
            }
            SymbolType::Tristate => match value.to_tristate() {
                Tristate::Yes => format!("{ident}=y"),
                Tristate::Module => format!("{ident}=m"),
                Tristate::No => format!("# {ident} is not set"),
            },
            SymbolType::Int | SymbolType::Hex | SymbolType::String => {
                format!("{ident}={value}")
            }
        }
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

pub fn generate(evaluated: &EvaluatedConfig) -> Generated {
    CodeGenerator::new().generate(evaluated)
}

#[cfg(test)]
mod tests {
    use super::CodeGenerator;
    use crate::domain::{
        AssignmentSet, DefaultValue, Evaluator, Expression, Limits, Symbol, SymbolTable,
        SymbolType, Value,
    };

    #[test]
    fn emits_typed_consts_and_dotconfig() {
        let limits = Limits::default();
        let mut table = SymbolTable::new();
        let mut foo = Symbol::new("FOO", limits)
            .unwrap()
            .with_type(SymbolType::Bool);
        foo.defaults.push(DefaultValue {
            value: Expression::Constant(Value::Bool(true)),
            condition: None,
        });
        let mut size = Symbol::new("BUFFER_SIZE", limits)
            .unwrap()
            .with_type(SymbolType::Int);
        size.defaults.push(DefaultValue {
            value: Expression::Constant(Value::Int(128)),
            condition: None,
        });
        let mut name = Symbol::new("BOARD_NAME", limits)
            .unwrap()
            .with_type(SymbolType::String);
        name.defaults.push(DefaultValue {
            value: Expression::Constant(Value::String("qemu".into())),
            condition: None,
        });
        table.insert(foo, limits).unwrap();
        table.insert(size, limits).unwrap();
        table.insert(name, limits).unwrap();
        let evaluated = Evaluator::new(limits)
            .evaluate(table, &AssignmentSet::new())
            .unwrap();
        let generated = CodeGenerator::new().generate(&evaluated);
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_FOO: bool = true;")
        );
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_BUFFER_SIZE: u8 = 128;")
        );
        assert!(
            generated
                .config_rs
                .contains("pub const CONFIG_BOARD_NAME: &'static str = \"qemu\";")
        );
        assert!(generated.dotconfig.contains("CONFIG_FOO=y"));
        assert!(generated.rustc_cfgs.contains(&"CONFIG_FOO".to_string()));
    }

    #[test]
    fn integer_width_follows_value_and_range() {
        assert_eq!(CodeGenerator::rust_int_type(0, 16), "u8");
        assert_eq!(CodeGenerator::rust_int_type(0, 256), "u16");
        assert_eq!(CodeGenerator::rust_int_type(0, 70_000), "u32");
        assert_eq!(
            CodeGenerator::rust_int_type(0, i128::from(u32::MAX) + 1),
            "u64"
        );
        assert_eq!(CodeGenerator::rust_int_type(-1, 10), "i8");
        assert_eq!(CodeGenerator::rust_int_type(-200, 10), "i16");
    }
}
